### ISSUE TITLE
Latest CPAN release has test failures

### ISSUE THREAD

**Issue by eserte** [memowe/contenticious#16]
See http://matrix.cpantesters.org/?dist=Contenticious%200.35 for an overview. Most (all?) of the fails may be related to https://github.com/memowe/contenticious/issues/12 , so maybe it helps to just create a new release.

**Comment by memowe** [comment]
Thanks, @eserte, just uploaded a new release. Hope it works.

**Comment by memowe** [comment]
Latest release seems to work fine now.
